start-at-login = true

# Move mouse cursor to the focused window.
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

[gaps]

inner.horizontal = 8
inner.vertical = 8
outer.left = 8
outer.right = 8
outer.top = 8
outer.bottom = 8

[mode.main.binding]

# Focus windows.
alt-left = "focus left"
alt-down = "focus down"
alt-up = "focus up"
alt-right = "focus right"

# Move windows.
alt-shift-left = "move left"
alt-shift-down = "move down"
alt-shift-up = "move up"
alt-shift-right = "move right"

# Loop workspaces.
ctrl-alt-left = "workspace prev"
ctrl-alt-right = "workspace next"

# Resize windows.
alt-minus = "resize smart -50"
alt-equal = "resize smart +50"

# Layouts.
alt-slash = "layout tiles horizontal vertical"
alt-comma = "layout accordion horizontal vertical"

# Fullscreen.
alt-f = "fullscreen"

# Workspaces.
alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-n = "workspace N"
alt-s = "workspace S"
alt-t = "workspace T"
alt-c = "workspace C"
alt-b = "workspace B"

# Move window to workspace and focus.
alt-shift-1 = "move-node-to-workspace --focus-follows-window 1"
alt-shift-2 = "move-node-to-workspace --focus-follows-window 2"
alt-shift-3 = "move-node-to-workspace --focus-follows-window 3"
alt-shift-n = "move-node-to-workspace --focus-follows-window N"
alt-shift-s = "move-node-to-workspace --focus-follows-window S"
alt-shift-t = "move-node-to-workspace --focus-follows-window T"
alt-shift-c = "move-node-to-workspace --focus-follows-window C"
alt-shift-b = "move-node-to-workspace --focus-follows-window B"

[[on-window-detected]]
if.app-id = "notion.id"
run = "move-node-to-workspace N"

[[on-window-detected]]
if.app-id = "com.tinyspeck.slackmacgap"
run = "move-node-to-workspace S"

[[on-window-detected]]
if.app-id = "com.github.wez.wezterm"
run = "move-node-to-workspace T"

[[on-window-detected]]
if.app-id = "com.todesktop.230313mzl4w4u92"
run = "move-node-to-workspace C"

[[on-window-detected]]
if.app-id = "com.google.Chrome"
run = "move-node-to-workspace B"
