"$schema" = "https://starship.rs/config/schema.json"

add_newline = false
command_timeout = 1000
scan_timeout = 500

format = """
$directory\
$git_branch\
$git_status\
$cmd_duration
$line_break\
$character"""

[character]
success_symbol = "[❯](bold #b8bb26)"
error_symbol = "[❯](bold #fb4934)"
vimcmd_symbol = "[❯](bold #83a598)"

[directory]
style = "bold #83a598"
truncation_length = 3
truncate_to_repo = true
read_only = "  "
read_only_style = "bold #fb4934"

[git_branch]
symbol = ""
format = "on [$branch]($style) "
style = "bold #b8bb26"

[git_status]
style = "bold #fabd2f"
format = "([\\[$all_status$ahead_behind\\]]($style) )"

[cmd_duration]
min_time = 2_000
style = "bold #928374"
format = "took [$duration]($style) "
